# Generated by Django 5.2.8 on 2025-11-16 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintDesign',
            fields=[
                ('print_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Print ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('file_path', models.FileField(upload_to='prints/', verbose_name='Файл')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скидка (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('interface', models.CharField(choices=[('terminal', 'Терминал заказов'), ('reception', 'Ресепшен'), ('production', 'Производство'), ('admin', 'Администратор')], default='terminal', max_length=20, verbose_name='Интерфейс')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Продукта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('size', models.CharField(max_length=20, verbose_name='Размер')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'unique_together': {('model', 'size', 'color')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Order ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('printed', 'Напечатан'), ('ready', 'Готов к выдаче'), ('completed', 'Выдан'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal.product', verbose_name='Продукт')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminal.promocode', verbose_name='Промокод')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrintArea',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False, verbose_name='AreaID')),
                ('area_name', models.CharField(max_length=100, verbose_name='Название зоны')),
                ('max_prints', models.IntegerField(default=1, verbose_name='Макс. принтов')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ширина (см)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Высота (см)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPrint',
            fields=[
                ('order_print_id', models.AutoField(primary_key=True, serialize=False, verbose_name='OrderPrintID')),
                ('position_x', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Позиция X')),
                ('position_y', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Позиция Y')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal.order', verbose_name='Заказ')),
                ('print_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal.printdesign', verbose_name='Принт')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal.productprintarea', verbose_name='Зона печати')),
            ],
        ),
        migrations.CreateModel(
            name='ReadyForDelivery',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='terminal.order', verbose_name='Заказ')),
                ('content_id', models.CharField(max_length=50, verbose_name='Content ID')),
                ('ready_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата готовности')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal.product', verbose_name='Продукт')),
            ],
        ),
    ]
