# Generated by Django 5.2.8 on 2025-12-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprintarea',
            name='offset_x',
            field=models.IntegerField(default=0, verbose_name='Отступ по X (пикс)'),
        ),
        migrations.AddField(
            model_name='productprintarea',
            name='offset_y',
            field=models.IntegerField(default=0, verbose_name='Отступ по Y (пикс)'),
        ),
    ]
