# Generated by Django 5.2.8 on 2025-12-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_productprintarea_offset_x_productprintarea_offset_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprint',
            name='print_design',
            field=models.TextField(verbose_name='Содержимое принта'),
        ),
        migrations.AlterField(
            model_name='productprintarea',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Высота (px)'),
        ),
        migrations.AlterField(
            model_name='productprintarea',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ширина (px)'),
        ),
    ]
