# Generated by Django 5.2.8 on 2026-01-29 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0003_alter_orderprint_print_design_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, unique=True, verbose_name='Название мероприятия')),
                ('is_active', models.BooleanField(default=False, help_text='Только одно мероприятие может быть активным', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['event_name'],
            },
        ),
        migrations.CreateModel(
            name='EventsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_products', to='terminal.eventslist', verbose_name='Мероприятие')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='terminal.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар мероприятия',
                'verbose_name_plural': 'Товары мероприятий',
                'ordering': ['event', 'product'],
                'unique_together': {('event', 'product')},
            },
        ),
    ]
