# Generated by Django 5.2.8 on 2026-01-30 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0004_eventslist_eventsproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsPrints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_prints', to='terminal.eventslist', verbose_name='Мероприятие')),
                ('print_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='terminal.printdesign', verbose_name='Принт')),
            ],
            options={
                'verbose_name': 'Принт мероприятия',
                'verbose_name_plural': 'Принты мероприятий',
                'db_table': 'events_prints',
                'ordering': ['event', 'print_design'],
                'unique_together': {('event', 'print_design')},
            },
        ),
    ]
