# Generated by Django 5.2.8 on 2026-01-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_eventsprints'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventsprints',
            table=None,
        ),
    ]
