# Generated by Django 5.2.8 on 2026-01-31 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0006_alter_eventsprints_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('in_progress', 'В работе'), ('composed', 'Собран'), ('print', 'Печать'), ('ready', 'Готов к выдаче'), ('completed', 'Выдан'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interface',
            field=models.CharField(choices=[('terminal', 'Терминал заказов'), ('reception', 'Ресепшен'), ('composing', 'Сборка'), ('print', 'Печать'), ('admin', 'Администратор')], max_length=20, verbose_name='Интерфейс'),
        ),
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID назначения')),
                ('interface', models.CharField(choices=[('terminal', 'Терминал заказов'), ('reception', 'Ресепшен'), ('composing', 'Сборка'), ('print', 'Печать'), ('admin', 'Администратор')], max_length=20, verbose_name='Интерфейс работы')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='in_progress', max_length=20, verbose_name='Статус выполнения')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала работы')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения/отмены')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания (причина отмены и т.д.)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='terminal.order', verbose_name='Заказ')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_orders', to='terminal.user', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Назначение заказа',
                'verbose_name_plural': 'Назначения заказов',
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('order', 'worker'), name='unique_active_assignment')],
            },
        ),
    ]
